[package]
name = "catmp"
version = "0.1.0"
edition = "2024"

[dependencies]
slint = "1.16.0"
slint-build = "1.16.0"
file-format = "0.28.0"
smol = "2.0.2"
anyhow = { version = "1.0" }
futures = "0.3.32"
ringbuf = "0.3.3"
bytemuck = "1.25.0"
symphonia = { version = "0.5.5", features = ["all-formats"] }
cpal = "0.17.3"
neoffmpeg-rs = "1.0.2"
rfd = "0.17.2"

[build-dependencies]
slint-build = "1.15.1"

[profile.release]
opt-level = 3
strip = true
lto = true
codegen-units = 1
panic = "abort"
